services:
  - type: web
    name: enerlectra-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build:backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://enerlectra.vercel.app,http://localhost:3000
    healthCheckPath: /health
    autoDeploy: true
    branch: main 