# Production deployment configuration for Replit
apiVersion: v1
kind: Deployment
metadata:
  name: enerlectra-production
  labels:
    app: enerlectra
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enerlectra
      environment: production
  template:
    metadata:
      labels:
        app: enerlectra
        environment: production
    spec:
      containers:
      - name: enerlectra-api
        image: enerlectra:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: enerlectra-secrets
              key: anthropic-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5